### ISSUE TITLE
Nstack does not have support in Xcode 14.3 via cocoapods, can not configure Nstack.

### ISSUE THREAD

**Issue by istiakmorsalinmlbd** [nstack-io/nstack-ios-sdk#109]
I tried to set up Nstack with cocoapods on Xcode 14.3 on the M2 apple silicon. 
My cocoapods version 1.12.0
Here is how I tried to integrate in the podfile 
```pod 'NStackSDK', '~> 5.1.4'``` 

I am trying to configure nstack like this below: 

```
import NStackSDK
class NStackConfigurator: AppConfigurationProtocol {
    
    func setup(withApplication application: UIApplication, launchOptions: [UIApplication.LaunchOptionsKey : Any]?) {
        
        var nStackConfig = Configuration(plistName: "NStack",
                                         environment: .production,
                                         localizationClass: Localizations.self)
        nStackConfig.updateOptions = [.onDidBecomeActive]
        NStack.start(configuration: nStackConfig, launchOptions: launchOptions)
        NStack.sharedInstance.localizationManager?.updateLocalizations()   
    }
}
```

But getting the following error. Please check the screenshot: 

![Screenshot 2023-04-16 at 12 15 06 AM](https://user-images.githubusercontent.com/64763332/232266035-610d2f78-d971-47aa-a344-6ba270a32336.png)

Under the above circumstances, what could be the possible way to use nstack in Xcode 14.3? I have tried with carthage but that is also not working. Please help me here.

**Comment by Istiakmorsalin** [comment]
Using Nstack version 5.1.7 was enough to fix the issue.

**Comment by mariusc** [comment]
Glad to hear it works now. In this case, I'm closing this issue
