### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by chriscombs** [nstack-io/nstack-ios-sdk#40]
It would be nice to have a Demo project that showcased all of the features you can find in NStack. 

- [x] Localization
- [x] In-app language picker
- [ ] Versions 
- [x] Feedback
- [ ] Rate reminder
- [x] Responses and Collections
etc.

**Comment by mariusc** [comment]
Also include an example of multiple languages in the same app and an in-app language picker

**Comment by mariusc** [comment]
Should this be a separate repo? Or a separate Xcode project in this repo?
Personally, I'm leaning towards keeping it in this repo, but I don't have a strong preference

**Comment by mariusc** [comment]
Closing this as "good enough" for now. For further improvements, let's open new issues
