### ISSUE TITLE
Using SKLocalizations type instead of Localizations as LocalizationModel crashes the SDK

### ISSUE THREAD

**Issue by jakobmygind** [nstack-io/nstack-ios-sdk#66]
I don't know if it is supposed to be used for translations, but if not it would be nice to add to the documentation, as I was hunting this crash for a while before it occurred to me to use the other type

So this works: 

```Swift
 let config = NStackSDK.Configuration(appId: "xx", restAPIKey: "xx", localizationClass: Localizations.self, environment: .debug)
```

This crashes
```Swift
 let config = NStackSDK.Configuration(appId: "xx", restAPIKey: "xx", localizationClass: SKLocalizations.self, environment: .debug)
```

**Comment by mariusc** [comment]
Yeah, we need to update and improve the documentation; currently, the most relevant one we have is probably in the [release notes for the 5.0 version](https://github.com/nstack-io/nstack-ios-sdk/releases/tag/5.0-beta), where no one can find it 🙈

**Comment by jakobmygind** [comment]
> Yeah, we need to update and improve the documentation; currently, the most relevant one we have is probably in the [release notes for the 5.0 version](https://github.com/nstack-io/nstack-ios-sdk/releases/tag/5.0-beta), where no one can find it 🙈

Thanks, @mariusc !
